"""Scans handbook content for glossary term variants.

The glossary terms are stored as ### headings in glossary.md.
For each glossary term, this script looks for case and plural variants that
actually appear in handbook content and writes them to variant_terms.txt.

Headings, table header cells, existing links, glossary.md, and tests.md
are excluded so the scan follows the glossary behavior used on the site.
"""

# Imports

# logging reports problems found while generating the variant terms
# re is Python's regex module
# unicodedata lets us fold accented letters back to a plain letter for sorting
# Path handles the input and output file locations
# here builds file paths from the project root
# date adds the generation date to the variant_terms file header
# inflect generates plural forms to search for

import logging
import re
import unicodedata
from pathlib import Path
from herepath import here
from datetime import date
import inflect


# Set up the logger
log = logging.getLogger(Path(__file__).stem)

# Get the script name from this Python file for warning messages.
SCRIPT_NAME = Path(__file__).stem

# SETTINGS

# Folder containing the handbook Markdown pages
DOCS_SOURCE = here("docs")

# Glossary source file
GLOSSARY_SOURCE = here("docs", "glossary.md")

# Output file
VARIANT_OUTPUT = here("tools", "variant_terms.txt")

# Markdown pages that should not be scanned for glossary variants.
# tests.md exists only on the glossary test site and can be removed here
# when the scanner moves into the full handbook.
EXCLUDED_PAGES = {
    "glossary.md",
    "tests.md",
}

# Format the generation date for the variant file header.
# Format is Sep 27, 2026
generation_date = f"{date.today():%b} {date.today().day}, {date.today().year}"

# Comments added to the top of the generated variant file.
HEADER = f"""# Generated: {generation_date}
#
# Term variants (or stemming) used when generating glossary tooltips.
# The first item on each line is the canonical term from glossary.md.
# Additional variants are exact forms found in the handbook, separated by |.
# Pattern: Canonical term | variant
# Example: Audit log | audit log | audit logs
# Each variant will use the same tooltip definition as its glossary term.
#
# Generated by tools/variant_scanner.py from glossary terms found in handbook content.
# Pages listed in EXCLUDED_PAGES are not scanned.
# Do not manually edit this file.
#
# Variant Terms List
"""

# Find Markdown headings.
HEADING = re.compile(r"^\s{0,3}#{1,6}\s+.*$", re.MULTILINE)

# Find Markdown table separator rows.
# The row immediately above a separator row is the table header and is excluded too.
TABLE_SEPARATOR = re.compile(r"^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$")

# Find inline Markdown links and images.
# Link text is excluded because glossary behavior is removed inside existing links.
MARKDOWN_LINK = re.compile(r"!?\[[^\]]*\]\([^)]*\)", re.DOTALL)


# Read the glossary terms.
glossary = Path(GLOSSARY_SOURCE).read_text(encoding="utf-8")
glossary_lines = glossary.splitlines()

terms = []

for line in glossary_lines:
    if line.startswith("### "):
        terms.append(line.removeprefix("### ").strip())


# Build the possible forms to search for.
# Each canonical glossary term is searched as written and as a possible plural.
# Matching is case-insensitive, but the exact form found in the handbook is preserved.

# inflect is a small, focused library for English word forms.
# It handles pluralization without adding a larger NLP dependency.
inflector = inflect.engine()

search_forms = {}

for term in terms:
    forms = {term}

    # Pluralize the final word so multi-word glossary terms stay intact.
    # Example: model cards
    if " " in term:
        beginning, final_word = term.rsplit(" ", 1)
        plural_word = inflector.plural_noun(final_word.lower())

        if plural_word:
            forms.add(f"{beginning} {plural_word}")
    else:
        plural_word = inflector.plural_noun(term.lower())

        if plural_word:
            forms.add(plural_word)

    search_forms[term] = forms


# Map each possible search form back to its canonical glossary term.
# Matching is case-insensitive, so different capitalizations use the same lookup key.
# Example: Model card, model card, and MODEL CARD all map back to Model card.
form_to_term = {}

for term, forms in search_forms.items():
    for form in forms:
        form_key = form.casefold()

        # Stop if the same search form could belong to more than one glossary term.
        # Otherwise, the later term would silently overwrite the earlier one.
        if form_key in form_to_term and form_to_term[form_key] != term:
            log.warning(
                f"HEY! From: [{SCRIPT_NAME}]. There's a problem. "
                f"Search form `{form}` matches more than one glossary term: "
                f"`{form_to_term[form_key]}` and `{term}`"
            )
            log.warning(
                "Rename or delete one. It must be fixed or no variants for you."
            )
            raise SystemExit(1)

        form_to_term[form_key] = term

# Search longer forms first so an overlapping glossary term is not split apart.
# Example: Fairness assessment must be matched before Fairness.
ordered_forms = sorted(
    (form for forms in search_forms.values() for form in forms),
    key=len,
    reverse=True,
)

# Overview of how case and plural matching works:
# canonical term: Model card
# -> inflect adds: Model cards
# -> re.IGNORECASE allows any capitalization of either form
# -> match.group(1) preserves the exact version found in the handbook

# Build one regex containing all canonical and plural forms.
# re.IGNORECASE finds capitalization variants without generating them separately.
# The text returned by the match still preserves the exact form used in the handbook.
term_pattern = re.compile(
    r"(?<!\w)(" + "|".join(re.escape(form) for form in ordered_forms) + r")(?!\w)",
    re.IGNORECASE,
)


# Find all Markdown pages under docs, including pages in subfolders.
handbook_pages = []

for page in Path(DOCS_SOURCE).rglob("*.md"):
    relative_page = page.relative_to(Path(DOCS_SOURCE)).as_posix()

    if relative_page not in EXCLUDED_PAGES:
        handbook_pages.append(page)

handbook_pages = sorted(handbook_pages)


# Scan handbook content for exact term forms.
variants = {term: set() for term in terms}

for page in handbook_pages:
    markdown = page.read_text(encoding="utf-8")

    # Remove headings.
    markdown = HEADING.sub(" ", markdown)

    # Remove table header rows and their separator rows.
    page_lines = markdown.splitlines()

    for index, line in enumerate(page_lines):
        if TABLE_SEPARATOR.match(line):
            if index > 0:
                page_lines[index - 1] = ""

            page_lines[index] = ""

    markdown = "\n".join(page_lines)

    # Remove existing links and images.
    markdown = MARKDOWN_LINK.sub(" ", markdown)

    # Treat Markdown line wrapping as spaces while scanning.
    markdown = re.sub(r"\s+", " ", markdown)

    # Record the exact surface form found in the handbook.
    # Scan the handbook text for glossary forms.
    # found is the exact spelling and capitalization used in the handbook.
    # casefold() is used only to look up which canonical glossary term owns that form.
    for match in term_pattern.finditer(markdown):
        found = match.group(1)
        canonical_term = form_to_term[found.casefold()]

        # The canonical form is already supplied by glossary.md, so only store
        # handbook forms that differ from it.
        if found != canonical_term:
            variants[canonical_term].add(found)


# Sort canonical terms alphabetically.
# Accented letters are folded to their plain form for sorting.
variant_entries = sorted(
    ((term, variants[term]) for term in terms if variants[term]),
    key=lambda entry: (
        unicodedata.normalize("NFKD", entry[0])
        .encode("ascii", "ignore")
        .decode("ascii")
        .lower()
    ),
)


# Build the output lines.
output_lines = []

for term, found_variants in variant_entries:
    sorted_variants = sorted(
        found_variants,
        key=lambda variant: (
            unicodedata.normalize("NFKD", variant)
            .encode("ascii", "ignore")
            .decode("ascii")
            .lower(),
            variant,
        ),
    )

    output_lines.append(" | ".join([term, *sorted_variants]))


# Write the generated variant terms file.
Path(VARIANT_OUTPUT).write_text(
    HEADER + "\n" + "\n".join(output_lines) + "\n",
    encoding="utf-8",
)

# Count all variants found across the glossary terms.
variant_count = sum(len(found_variants) for _, found_variants in variant_entries)

print(
    f"HEY! The variant scanner did the tedious work for you: "
    f"{variant_count} variants found for {len(output_lines)} glossary terms "
    f"across {len(handbook_pages)} handbook pages. "
    f"Go inspect {VARIANT_OUTPUT.name}."
)
